# Generated by Django 5.2.17 on 2026-09-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='The passage the player types.')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TypingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('classic', 'Classic Sprint'), ('car_race', 'Car Race'), ('battle', 'Boss Battle'), ('rocket', 'Rocket Launch'), ('word_rain', 'Word Rain')], max_length=20)),
                ('wpm', models.PositiveIntegerField()),
                ('accuracy', models.PositiveIntegerField(help_text='Percent, 0-100')),
                ('duration_seconds', models.FloatField()),
                ('outcome', models.CharField(blank=True, help_text="e.g. 'won'/'lost' for Car Race, Boss Battle, Rocket Launch and Word Rain.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_attempts', to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='typing_game.typingtext')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
