# Generated by Django 5.2.17 on 2026-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Last day the user solved a challenge, for streak tracking', null=True),
        ),
    ]
