# Generated by Django 5.2.17 on 2026-09-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['id']},
        ),
    ]
