# Generated by Django 5.2.17 on 2026-09-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_testcase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-id']},
        ),
    ]
