# Generated by Django 5.2.17 on 2026-09-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_seed_quiz_master_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='requirement_type',
            field=models.CharField(choices=[('challenges_solved', 'Challenges solved'), ('streak_days', 'Streak (days)'), ('quiz_score', 'Quiz score (%)')], max_length=30),
        ),
    ]
