# Generated by Django 5.2.17 on 2026-09-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_badge_requirement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='requirement_type',
            field=models.CharField(choices=[('challenges_solved', 'Challenges solved'), ('streak_days', 'Streak (days)'), ('quiz_score', 'Quiz score (%)'), ('typing_wpm', 'Typing speed (WPM)')], max_length=30),
        ),
    ]
