# Generated by Django 5.2.17 on 2026-09-18 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcadeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('snake', 'Snake'), ('memory_match', 'Memory Match'), ('reaction_time', 'Reaction Time')], max_length=20)),
                ('score', models.PositiveIntegerField(help_text='Higher is always better, across every game.')),
                ('detail', models.CharField(blank=True, help_text="Human-readable summary, e.g. '14 food, length 17'.", max_length=100)),
                ('duration_seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcade_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
