# Generated by Django 5.2.17 on 2026-09-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcadeattempt',
            name='game',
            field=models.CharField(choices=[('snake', 'Snake'), ('memory_match', 'Memory Match'), ('reaction_time', 'Reaction Time'), ('archery', 'Archery'), ('chess', 'Chess')], max_length=20),
        ),
    ]
