# Generated by Django 5.2.17 on 2026-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0003_alter_arcadeattempt_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcadeattempt',
            name='game',
            field=models.CharField(choices=[('snake', 'Snake'), ('memory_match', 'Memory Match'), ('reaction_time', 'Reaction Time'), ('archery', 'Archery'), ('chess', 'Chess'), ('car_racing', 'Car Racing'), ('bounce', 'Bounce')], max_length=20),
        ),
    ]
